# Generated by Django 3.1.8 on 2021-05-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20210506_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starship',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Starship', 'verbose_name_plural': 'Starships'},
        ),
    ]
