# Generated by Django 3.1.8 on 2021-05-15 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20210508_0403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='vehiclepassenger',
            options={'managed': True, 'ordering': ['vehicle', 'passenger'], 'verbose_name': 'Vehicle Passenger', 'verbose_name_plural': 'Vehicle Passenger'},
        ),
        migrations.CreateModel(
            name='SpeciesCharacter',
            fields=[
                ('species_character_id', models.AutoField(primary_key=True, serialize=False)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.person')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.species')),
            ],
            options={
                'verbose_name': 'Species Character',
                'verbose_name_plural': 'Species Characters',
                'db_table': 'species_character',
                'ordering': ['species', 'character'],
                'managed': True,
                'unique_together': {('species', 'character')},
            },
        ),
    ]
